name: Check coverage
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [master, main]
    paths:
      - src/**
      - tests/**
      - phpunit.xml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-coverage:
    name: Generate coverage
    uses: ./.github/workflows/generate-coverage.yml
  merge-coverage:
    name: Merge coverage
    needs: generate-coverage
    uses: michaelbaril/shared/.github/workflows/merge-coverage.yml@main
  check-coverage:
    name: Check coverage
    needs: merge-coverage
    uses: michaelbaril/shared/.github/workflows/check-coverage.yml@main
