name: "Publish documentation"
on:
  push:
    branches: [master, main]
    paths:
      - README.md
      - doc/**.md
      - markdown-to-html.json
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish-doc:
    uses: ./.github/workflows/reusable-publish-doc.yml

