name: Publish coverage
on:
  push:
    branches: [master, main]
    paths:
      - src/**
      - tests/**
      - phpunit.xml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-coverage:
    name: Generate coverage
    uses: ./.github/workflows/generate-coverage.yml
  merge-coverage:
    name: Merge coverage
    needs: generate-coverage
    uses: michaelbaril/shared/.github/workflows/merge-coverage.yml@main
    with:
      html: true
  publish-coverage:
    name: Publish coverage
    needs: merge-coverage
    uses: michaelbaril/shared/.github/workflows/publish-coverage.yml@main
