name: "Add coverage comment to PR"
on:
  workflow_call:
jobs:
  generate-coverage-report:
    name: Add coverage comment
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura.xml
          badge: true
          format: markdown
          fail_below_min: false
          output: both
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
